[general]
REDIRECT_URI = "https://tailortalk-sm12.streamlit.app"

[google_oauth]
client_id = "991092210243-kf83tj62fgfnca6535bj1krho0p1pu9v.apps.googleusercontent.com"
client_secret = "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"
