[general]
REDIRECT_URI = "https://tailortalk-sm12.streamlit.app"

[google_oauth]
client_id = "991092210243-si6iqlks1hkei9n15vvtaahlps54sgra.apps.googleusercontent.com"
client_secret = "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"
